### ISSUE TITLE
[BUG] 3.0.0 settings system doesnt load settings after quitting save

### ISSUE THREAD

**Issue by TheanMcGarity** [ThatFinnDev/SR2E#44]
The settings system doesn't load the settings categories or anything else after closing a save. Save settings will still apply to existing saves hwoever.

You will get this error by:
- Loading a save file
- Quitting to main menu
- Opening new save ui or options ui
- find the error

![image](https://github.com/user-attachments/assets/41f4d241-a656-46b6-94ba-226b17dd23dc)

```
[08:57:25.078] [SR2E] System.Exception: A custom settings button already has this id: testButton1
   at SR2E.Buttons.CustomSettingsCreator.Create(BuiltinSettingsCategory category, LocalizedString label, LocalizedString description, String id, Boolean applyImmediately, Boolean confirm, OnSettingEdited modifyCallback, OptionValue[] values) in C:\Users\Thean Mcgarity\OneDrive\Documents\aaa\SR2E\SR2EssentialsMod\Buttons\CustomSettingsButton.cs:line 171
   at SR2E.SR2EEntryPoint.<>c.<OnSceneWasLoaded>b__46_2(Object _, EventArgs _) in C:\Users\Thean Mcgarity\OneDrive\Documents\aaa\SR2E\SR2EssentialsMod\EntryPoint.cs:line 336
   at SR2E.SR2EEntryPoint.OnSceneWasLoaded(Int32 buildIndex, String sceneName) in C:\Users\Thean Mcgarity\OneDrive\Documents\aaa\SR2E\SR2EssentialsMod\EntryPoint.cs:line 408
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
```

**Comment by LiamTater** [comment]
should be fixed, closing this issue

**Comment by TheanMcGarity** [comment]
@LiamTater you cant do that lol. This bug is the reason the Settings Save System has been disabled, and we aren't actively working on it. It is not fixed, it is just disabled.

**Comment by LiamTater** [comment]
settings system works really well on 3.1.0

**Comment by TheanMcGarity** [comment]
closing this bc people are dumb
